name: âš¡ Package version bump

on:
  release:
    types: [created]

jobs:
  bump:
    name: ğŸ†• Version bump
    runs-on: ubuntu-latest
    steps:

    - name: â¬‡ï¸ Checkout repo
      uses: actions/checkout@v4
      
    - name: â« Bumping version
      uses: phips28/gh-action-bump-version@v11.0.4
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        minor-wording: feat,minor
        major-wording: BREAKING CHANGE,major
          
